### PR TITLE
feature(interventions): review and sign fields + overall style changes

### PR DESCRIPTION
**Pull request by adi130987**

### CODE REVIEW

**Comment by adi130987** [comment]
connects unicef/etools-issues#396

**Comment by adi130987** [comment]
@robertavram, @ntrncic we need new properties on intervention details object:
- `submitted_to_prc` - Boolean
- `signed_pd_document_file` - String(file url)
- `signed_pd_document` - String(file url) or File

UI changes are depending on my question from unicef/etools-issues#396

**Comment by robertavram** [comment]
ok.. I will look into this.. by the end of this week we'll have api changes for this... this needs to be merged in develop before anything else..

**Comment by robertavram** [comment]
@adi130987 make sure not to send submitted_to_prc bool field to the server... 
backend branch to test against for now: https://github.com/unicef/etools-issues/issues/429

**Comment by adi130987** [comment]
@robertavram and how should I know to show PRC fields? Should I compute this field from PRC submitted/reviewed/document fields?

**Comment by robertavram** [comment]
@adi130987 we're returing it from the backend.. computed

**Comment by adi130987** [comment]
@robertavram ok, cool

**Comment by robertavram** [comment]
removing api changes needed field as api fields are now in Develop

**Pull request merged**
