### PR TITLE
Planned budget redesign

### PR DESCRIPTION
**Pull request by acory**
connects unicef/etools-issues#397

### CODE REVIEW

**Comment by adi130987** [comment]
After API is changed we can test this.
Make sure to remove the `// TODO: remove once the API is changed / this was just for testing` and related code.

**Comment by adi130987** [comment]
fix `planned_budget` in `_formatResponseDataForDexie`, use backend `planned-budget-updates`

**Comment by robertavram** [comment]
Local currency should default to the Workspace local currency.
Local Currency dropdown is behaving weird when adding a new PD (searchbar needs to be scrolled to)

**Comment by acory** [comment]
@robertavram  About this 'Local currency should default to the Workspace local currency'.
Local currency does not come on the user profile , also currencies do not contain info about countryId so I can find the localCurrency by current country .
Any sugestions here? It the local currency available somewhere or api change are needed?

**Comment by adi130987** [comment]
new branch in backend for local currency `add_currency_api`
the endpoint is /api/v2/users/country/

**Pull request merged**
